 # pool configs
_pool: &_pool
  pool_max_active: 10
  pool_max_active_sec: 300
  pool_max_idle: 5
  pool_max_idle_sec: 600

# database configs
_base: &_base
  type: "mysql"
  host: "127.0.0.1"
  port: "3306"
  user: "root"
  pass: "passwd"
  charset: "utf8"
  <<: *_pool

# db drivers list
drivers:
  base:
    db: gb_base
    <<: *_base
  user_shard_1:
    db: gb_user_shard_1
    <<: *_base
  user_shard_2:
    db: gb_user_shard_2
    <<: *_base
  user_shard_3:
    db: gb_user_shard_3
    <<: *_base
  user_shard_4:
    db: gb_user_shard_4
    <<: *_base
  log_shard_1:
    db: gb_log_shard_1
    <<: *_base
  log_shard_2:
    db: gb_log_shard_2
    <<: *_base

# db cluster configs
clusters:
  user:
    type: mysql
    algo: hash
    seq_id: id
    shards:
    - driver: user_shard_1
      mod_res: 1
    - driver: user_shard_2
      mod_res: 2
    - driver: user_shard_3
      mod_res: 3
    - driver: user_shard_4
      mod_res: 0
  log:
    type: mysql
    algo: range
    seq_id: id
    shards:
    - driver: log_shard_1
      fr_num: 1
      to_num: 500
    - driver: log_shard_2
      fr_num: 501
      to_num: 1000
      

